language: go
go:
- '1.13'
sudo: required
dist: xenial
env:
  global:
  - AWS_REGION=us-east-1
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_ACCESS_KEY_ID=AKIA2BCIPONCZZBWXJNR
  - IAM_ACCESS_KEY_ID=AKIA2BCIPONCQ7KY4PEP
  - REGISTRY_USER=elotlbuild
  - TERRAFORM_VERSION=0.12.21
  - KUBECTL_VERSION=1.18.0
  - IMG_VERSION=0.5.7
  - secure: eQV5LiSp5XP7pL4gFYR98uL8aMdmeI5J5h3oOsRZ8fEBVFB0XBX0QDmK6zpaxAx2GoHfFC6ioUdNQjiVmnatwRHnnmxlplD8w99LXcvYkdfS6mtbyhdd2gZNv3gypIFqzyG73zqqhosNSUou1H8GSMWaQSk+P1Y6W7jHKsPEtrV5fepwu6tSpIK+DZbN2mrbyKdKMgWkdAPd/ni++bLDrvwlsoC8MOyWLerDnjRdC/Enzp4OgP9XR/JcqaNyXGLhMRLrN/PwWUk6mayjiVdGk9MLM+YuzCaVaqmtlHZMQHQQzP8r8KO4wZt+ApfNkVlwj44+ya7YoMkSguS5U4AmC0I3NntwhA4L8tpezk/FhSF0FwmP2MDKbWajYWtptThoXRQ5yU/UTJD/hWPofZPm9halZs7yqtoYNLXQWGfS06zROMyLoDOI7uw8b3VSSxQwVjcy8zjmJ/X5I/Dpl/QXsFGaU3u3u/Q0gE4V7ve/9fhbcittq1pRamcVvvZE/jUiXxWEiVEQ39W2dF/Fsp71nvm9Q7vTkgFKPtZV+lwFykTf9gg8vdbRTJ2qlYz668mQ0B+XUhueR+gxaDV+pIFKHRM+/B32fakTwBkXFHGtonodSL8TCeOydpmWLzJ4KexHAjL9AaUoqj4XKfQtAmtNppPmHpScONfhEZ65V+EnXiE=
  - secure: rwyN3nyJ0+ghzNDC5TmpTZNHFvxdapiyFGTSNgpgsdzBXrBVYtPAc1ygAMYYauS8GyrTTg55wbrZUTrSspWirecwVprtLg3Lby/VacXz/qCtZ5wBsYhWJTkbgX0q/H9j3JqGTPUjJORRe5krRHmCrW2nhy+FrE731IcKgItspCGyXoGbh/O3z5yIZIU9NWKX/BqgzjUf7cYdkm25dphQOUkNJOBzeG7Nv7DumzC0V524F4s2GK4Eqp4P/SAENDjdmnwMw+SC1peikAo1XHmWgz72EvVKncF7b6PVs80rnAOEwNg1Hs8B90VWiZpW+qPWBhJuNjoXOTdNxjaAs0y5S/9BLBNcqvIp6Kj1/QtMuCbk63pVYa9OiUv+2XLlJJ4om0BcqE/CghQvhKtOuNN9gxSHjXP7RP1yqyBMVY3jsXQHU9IZcpbaF2ZmRB587gHCUcDXZbz+wLvBLnw0UjKxCdcJrop9zg7ylwo4r5h2ojfhfXt1lYqH2Lvpz8n98uHYVOvgdShxQsDmw1W37ggNB4jMVxcv7atUBI8jzYMNOg80Qjp2ghuGjYon9KQTMis8ykBg6qOFLwS62cWe6GbZ6LQmjhLg/ZOOieD512p/Re/s47e5cakuHqC//VY8rqDPiEsXCHc0lhZ1HWy5akqes/gYkvoGsNWGUcT5sKdIedg=
  - secure: enUIOI5sIXXdxms1iadphnAZF5SUFl4SaTqMpXYKnRDgS8B9bjO5LsiZTqJqQ84v9MbndcJ44cpWvs9pvTgIHhO5O7mxD/TPWqqAOLAzbIAWaaa/mu+jx9WEUoDh1mAf//5IZrI/FJmUm6HNxu0pxepdogMGfWx5ngbqqM41Eu726xY7Yq9GESipK+bNgMNyPL/K+J62EVfDmKsQRVAZLMN6GEw4zU8kGoVhIrzBm8Tp67kE9q3seOqlx4BwG0gG1PtVT3HRBO7OVy5e+6iKEVCQfrZYocKT+MpRFe7moS/YMO8M/Mt1MmcOAjGU6T57ZJDIBvnGhov+LMjEsNBNozL1iombVew+R1HWRQsVEKU298WPf+yEbl2KQfVkk+7n8vCmgPG2S4W5fmE1Dq/0Ep2ocIFI1HmJSkImCm8o7znL7URzLLx6FloQ8W2Pn9ux4Jac0EbRcQfw/rJkce7n7QkprR/1/gM/C8lYUXKPHgDWjBdklSc4i388EGOmXOMDJh2jRYhpUy6QcJePyXJVxnItPJixmK0DsFU40ryffsANuAoSa8Gsg/2qLJXBfZqHL0l3AfTuZBJSXVc6Qi/DMQdcnSD/cPd1+Wo9kQoMyB6DTET7vCQ+ShUKVNFQZKC/tCuZv2oBE7Ity4UhNpVFBHngCCV5rco78U0CopRRHHs=
before_script:
- git fetch --unshallow || true
- pip install awscli --upgrade --user
- pip install jq --upgrade --user
- go get -u k8s.io/gengo/examples/deepcopy-gen
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
  && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  && sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin/
- curl -LOs https://github.com/genuinetools/img/releases/download/v${IMG_VERSION}/img-linux-amd64
  && curl -LOs https://github.com/genuinetools/img/releases/download/v${IMG_VERSION}/img-linux-amd64.sha256
  && sed -i 's#/.*/img-linux-amd64#img-linux-amd64#g' img-linux-amd64.sha256
  && shasum -a 256 -c img-linux-amd64.sha256 2>&1
  && sudo install -m 0755 img-linux-amd64 /usr/local/bin/img
script:
- set -e
- make
- "./scripts/run_tests.sh"
- make img login-img push-img
- "./scripts/run_smoke_test.sh"
notifications:
  slack:
    secure: d4Y/cOEzbFc7RHwizwVsdaTCURsQ/Rmm2kyGgw3WboO7ijU0PRNTioktRxB5byJAhCI79bDJbLxwNRempIdSlzG4sL7UHK4Nyxb0t5XxBLDzqD1nJPL652r5oQ8W+ru9tMKtO4xWc2ELl3spe4Lb1pyXHCSpvkd++IgZBKbpOdaCs4XNWm94sVXVRPiJOs+0tlX+gYjnGkje91MaVYJM/XMWNxOut2t6BZ1raYm+mYJUSfC7CFJPAha8+1x8S7CEbJE8Xa63gV37HUDsZbZfYdpljm3/nd6cdJzDYf51Cvdwh/DUqcBvw2AUm8AMlMUF7hGkSTS0gTRkO7nkURkm6eGJesHp0aEGg24TFIFaCtcI4rPq49GDPKOmAJUHtWev1oPw2SCIXw4cDkulKoYzqj+amXSfXDVN3Uza3zVGY445Wd5VLkiEoCvvE06Hp4gjnDfvszTh9Kj/CK7x8e4BtPyuq0oxn64/SyoSb9CfZL0VqNar4hlms44CYMdnLGzf6Sicc7+Og1aC3cd5/GlVRTtNsaf6qHVtQbhW9lar2fjpO2B2KxiOLmAvwp6aSN+Zmwif/xGfwqAJnQllB3d/ewiTjK34RJiKDg6BSUecC2Dp8jSzv9qpXYWvjSHM2kgltXgs21q7Pm7L6ISdhn6ek23ASe0N85qyyrNglF79mWA=
