apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: virtual-kubelet
  name: virtual-kubelet
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-kubelet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: virtual-kubelet
        virtual-kubelet: ""
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: virtual-kubelet
                  operator: In
                  values:
                  - ""
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      containers:
      - command:
        - /virtual-kubelet
        - --provider
        - kip
        - --provider-config
        - /etc/virtual-kubelet/provider.yaml
        - --network-agent-secret
        - kube-system/vk-network-agent
        - --disable-taint
        - --klog.logtostderr
        - --klog.v=5
        image: elotl/virtual-kubelet:dev
        imagePullPolicy: Always
        name: virtual-kubelet
        env:
        - name: KUBELET_PORT
          value: "10666"
        - name: APISERVER_CERT_LOCATION
          value: /etc/kubelet-pki/kubelet.crt
        - name: APISERVER_KEY_LOCATION
          value: /etc/kubelet-pki/kubelet.key
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: data
          mountPath: /opt/kip/data
        - name: provider-yaml
          mountPath: /etc/virtual-kubelet
        - name: kubelet-pki
          mountPath: /etc/kubelet-pki
        - name: xtables-lock
          mountPath: /run/xtables.lock
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: virtual-kubelet
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: provider-data
      - name: kubelet-pki
        hostPath:
          path: /var/lib/kubelet/pki
          type: Directory
      - name: provider-yaml
        configMap:
          name: virtual-kubelet-config
          items:
          - key: provider.yaml
            path: provider.yaml
            mode: 0600
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: ""
