apiVersion: v1
kind: ServiceAccount
metadata:
  name: vk-network-agent
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: vk-network-agent
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - extensions
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: vk-network-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vk-network-agent
subjects:
- kind: ServiceAccount
  name: vk-network-agent
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vk-network-agent
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: vk-network-agent
type: kubernetes.io/service-account-token
