apiVersion: v1
cloud:
  aws:
    region: "us-east-1"
    accessKeyID: ""
    secretAccessKey: ""
etcd:
  internal:
    dataDir: /opt/kip/data
cells:
  bootImageSpec:
    owners: 689494258501
    filters: name=elotl-kip-*
  defaultInstanceType: "t3.nano"
  defaultVolumeSize: "20G"
  nametag: kip
  itzo:
    url: https://itzo-kip-download.s3.amazonaws.com
    version: latest
kubelet:
  cpu: "20"
  memory: "512Gi"
  pods: "200"
