apiVersion: v1
cloud:
  gce: {}
    # if the k8s node where kip will run doesn't have
    # https://www.googleapis.com/auth/compute scope then GCE
    # credentials for kip can be supplied in cloud.gce.credentials:
    #
    # credentials:
    #   clientEmail: FILL_IN
    #   privateKey: FILL_IN
etcd:
  internal:
    dataDir: /opt/kip/data
cells:
  bootImageSpec:
    project: elotl-kip
    image: elotl-kip-latest
  defaultVolumeSize: "10G"
  defaultInstanceType: e2-small
  nametag: vk
  itzo:
    url: https://itzo-kip-download.s3.amazonaws.com
    version: latest
kubelet:
  cpu: "100"
  memory: "512Gi"
  pods: "200"
