apiVersion: v1
cloud:
  gce:
    credentials:
      clientEmail: FILL_IN
      privateKey: FILL_IN
etcd:
  internal:
    dataDir: /opt/kip/data
cells:
  bootImageSpec:
    project: elotl-kip
    image: elotl-kip-latest
  defaultVolumeSize: "10G"
  defaultInstanceType: e2-small
  nametag: vk
  itzo:
    url: https://itzo-kip-download.s3.amazonaws.com
    version: latest
kubelet:
  cpu: "100"
  memory: "512Gi"
  pods: "200"
