apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-kubelet
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        name: virtual-kubelet
        envFrom:
        - secretRef:
            name: virtual-kubelet-secrets
