apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kip
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
      - name: provider-yaml
        configMap:
          name: kip-config
          items:
          - key: cloudinit.yaml
            path: cloudinit.yaml
            mode: 0600
          - key: provider.yaml
            path: provider.yaml
            mode: 0600
