apiVersion: v1
cloud:
  aws:
    # You can also use environment variables for region, access and secret key.
    region: us-east-1
    accessKeyID: ""
    secretAccessKey: ""
    vpcID: FILL_IN
    subnetID: FILL_IN
etcd:
  internal:
    dataDir: /opt/kip/data
cells:
  standbyCells:
  defaultInstanceType: t3.nano
  defaultVolumeSize: 15G
  bootImageSpec:
    owners: 689494258501
    filters: name=elotl-kip-*
  nametag: minikube
  itzo:
    url: https://itzo-kip-download.s3.amazonaws.com
    version: latest
# Optional, if kip needs to connect to cells via public IPs.
#  extraCIDRs:
#  - FILL_IN
#  extraSecurityGroups:
#  - FILL_IN
kubelet:
  cpu: "100"
  memory: "512Gi"
  pods: "200"
