apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kip
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kip
        envFrom:
        - secretRef:
            name: kip-secrets
