bases:
- ../../base
patchesStrategicMerge:
- statefulset.yaml
configMapGenerator:
- name: virtual-kubelet-config
  namespace: kube-system
  behavior: merge
  files:
  - cloudinit.yaml
  - provider.yaml
